### ISSUE TITLE
couple of issues with the grammar

### ISSUE THREAD

**Issue by mcorne** [Rieselhilfe/parseo#2]
very nice tool this parseo btw!
there is a few issues with the grammar:
- it does not find hejmen whereas accusative is allowed for adverbs, see rule 44 in https://lernu.net/gramatiko/akuzativo
- it should not recognize kiej as there is no plural for e correlatives, see rule 63 in https://lernu.net/gramatiko/tabelvortoj
- same for kioj, see rule 45 in https://lernu.net/gramatiko/tabelvortoj

**Comment by Rieselhilfe** [comment]
Thanks! Glad someone enjoys it. I will fix that. The lernu grammar overview is quite helpful, too. I didn't know about that.
Btw: I also made this into a website as a programming exercise. It would probably crash if more than a handful people actually used it at the same time but here it is, if you want to use parseo in a more convenient way: parseo.online
